// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(FikirHavuzuContext))]
    partial class FikirHavuzuContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserPermission", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.HasKey("UserId", "PermissionId")
                        .HasName("KullanıcıYetki_pkey");

                    b.HasIndex(new[] { "PermissionId" }, "IX_KullanıcıYetki_yetki_id");

                    b.ToTable("UserPermission", (string)null);
                });

            modelBuilder.Entity("api.Models.Evaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<bool>("IsPositive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_positive");

                    b.Property<Guid>("ProposalId")
                        .HasColumnType("uuid")
                        .HasColumnName("proposal_id");

                    b.Property<int>("Score")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Score"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Score"), null, null, 0L, 5L, null, null);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("Yorum_pkey");

                    b.HasIndex(new[] { "ProposalId" }, "IX_Değerlendirme_fikir_id");

                    b.HasIndex(new[] { "UserId" }, "IX_Değerlendirme_yaratıcı_id");

                    b.ToTable("Evaluation", (string)null);
                });

            modelBuilder.Entity("api.Models.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("id");

                    b.HasIndex(new[] { "Name" }, "YetkiAdı")
                        .IsUnique();

                    b.ToTable("Permission", (string)null);
                });

            modelBuilder.Entity("api.Models.Proposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("character varying(8192)")
                        .HasColumnName("explanation");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("purpose");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("title");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("topic");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("Fikir_pkey");

                    b.HasIndex(new[] { "UserId" }, "IX_Fikir_yaratıcı_id");

                    b.ToTable("Proposal", (string)null);
                });

            modelBuilder.Entity("api.Models.ProposalFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("File")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file");

                    b.Property<Guid>("ProposalId")
                        .HasColumnType("uuid")
                        .HasColumnName("proposal_id");

                    b.HasKey("Id")
                        .HasName("FikirDosya_pkey");

                    b.HasIndex(new[] { "ProposalId" }, "IX_FikirDosya_fikir_id");

                    b.ToTable("ProposalFile", (string)null);
                });

            modelBuilder.Entity("api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("GovernmentId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("government_ID");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("phone");

                    b.Property<string>("RegistrationNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("registration_no");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("surname");

                    b.HasKey("Id")
                        .HasName("Kullanıcı_pkey");

                    b.HasIndex(new[] { "GovernmentId" }, "Kullanıcı_kimlikNo_key")
                        .IsUnique();

                    b.HasIndex(new[] { "RegistrationNo" }, "Kullanıcı_sicilNo_key")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("UserPermission", b =>
                {
                    b.HasOne("api.Models.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("UserPermission_permission_id_fkey");

                    b.HasOne("api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("UserPermission_user_id_fkey");
                });

            modelBuilder.Entity("api.Models.Evaluation", b =>
                {
                    b.HasOne("api.Models.Proposal", "Proposal")
                        .WithMany("Evaluations")
                        .HasForeignKey("ProposalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Evaluation_proposal_id_fkey");

                    b.HasOne("api.Models.User", "User")
                        .WithMany("Evaluations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Evaluation_creator_id_fkey");

                    b.Navigation("Proposal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("api.Models.Proposal", b =>
                {
                    b.HasOne("api.Models.User", "User")
                        .WithMany("Proposals")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("yaratıcı_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("api.Models.ProposalFile", b =>
                {
                    b.HasOne("api.Models.Proposal", "Proposal")
                        .WithMany("ProposalFiles")
                        .HasForeignKey("ProposalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("ProposalFile_proposal_id_fkey");

                    b.Navigation("Proposal");
                });

            modelBuilder.Entity("api.Models.Proposal", b =>
                {
                    b.Navigation("Evaluations");

                    b.Navigation("ProposalFiles");
                });

            modelBuilder.Entity("api.Models.User", b =>
                {
                    b.Navigation("Evaluations");

                    b.Navigation("Proposals");
                });
#pragma warning restore 612, 618
        }
    }
}
